Update mr

diff --git a/mr b/mr
--- a/mr
+++ b/mr
@@ -491,6 +491,15 @@ is checked out, or updated. This provides an easy way to do things
 like permissions fixups, or other tweaks to the repository content,
 whenever the repository is changed.
 
+=item jobs
+
+If "jobs" is set, run the specified number of jobs in parallel.
+This can greatly speed up operations such as updates.
+
+Note that running more than 10 jobs at a time is likely to run afoul of
+ssh connection limits. Running between 3 and 5 jobs at a time will yield
+a good speedup in updates without loading the machine too much.
+
 =item VCS_action
 
 When looking for a command to run for a given action, mr first looks for
@@ -1449,6 +1458,16 @@ sub loadconfig {
 				next;
 			}
 
+			if ($parameter eq 'jobs') {
+				print "mr: setting --jobs to \"$value\"\n" if $verbose;
+				unless ($value =~ /^\d+$/) {
+					print "mr: error: --jobs must be numeric\n";
+					exit 2
+				}
+				$jobs=$value;
+				next;
+			}
+
 			if (! defined $section) {
 				$lineerror->("parameter ($parameter) not in section");
 			}
@@ -1487,7 +1506,7 @@ sub loadconfig {
 							push @toload, ["$chaindir/.mrconfig", $chaindir];
 						}
 					}
-			        }
+				}
 			}
 		}
 		else {
@@ -1637,24 +1656,26 @@ sub dispatch {
 
 sub help {
 	my $help=q#
-		case `uname -s` in
-			SunOS)
-			SHOWMANFILE="man -f"
-			;;
-			Darwin)
-			SHOWMANFILE="man"
-			;;
-			*)
-			SHOWMANFILE="man"
-			;;
-		esac
 		if [ ! -e "$MR_PATH" ]; then
 			error "cannot find program path"
 		fi
 		tmp=$(mktemp -t mr.XXXXXXXXXX) || error "mktemp failed"
 		trap "rm -f $tmp" exit
 		pod2man -c mr "$MR_PATH" > "$tmp" || error "pod2man failed"
-		$SHOWMANFILE "$tmp" || error "man failed"
+		showman() {
+			case `uname -s` in
+				SunOS)
+				man -f "$tmp"
+				;;
+				OpenBSD)
+				mandoc "$tmp" | ${PAGER:-more}
+				;;
+				*)
+				man "$tmp"
+				;;
+			esac
+		}
+		showman "$tmp" || error "man failed"
 	#;
 	exec($help) || die "exec: $!";
 }
@@ -1879,6 +1900,19 @@ sub getopts {
 	}
 }
 
+sub check {
+	my @env = qw(GIT_DIR GIT_INDEX_FILE GIT_OBJECT_DIRECTORY GIT_WORK_TREE VCSH_COMMAND VCSH_DIRECTORY VCSH_REPO_NAME);
+	my $error;
+	foreach (@env) {
+		if ($ENV{$_}) {
+			$error=1;
+			print STDERR "mr: environment variable '$_' is set.\n";
+		}
+	}
+	die ("mr: The variables above would lead to very interesting effects.
+    Unfortunately, most of those effects result in data loss so we stop here.\n") if $error;
+}
+
 sub init {
 	$SIG{INT}=sub {
 		print STDERR "mr: interrupted\n";
@@ -1914,6 +1948,7 @@ sub exitstats {
 
 sub main {
 	getopts();
+	check();
 	init();
 	help(@ARGV) if $ARGV[0] eq 'help';
 
@@ -1954,7 +1989,7 @@ lib =
 		if [ -z "$1" ] || [ -z "$2" ]; then
 			error "mr: usage: hours_since action num"
 		fi
-		for dir in .git .svn .bzr CVS .hg _darcs _FOSSIL_; do
+		for dir in .git .svn .bzr CVS .hg _darcs _FOSSIL_ .fslckout; do
 			if [ -e "$MR_REPO/$dir" ]; then
 				flagfile="$MR_REPO/$dir/.mr_last$1"
 				break
@@ -1988,7 +2023,7 @@ bzr_test = perl: -d "$ENV{MR_REPO}/.bzr"
 cvs_test = perl: -d "$ENV{MR_REPO}/CVS"
 hg_test  = perl: -d "$ENV{MR_REPO}/.hg"
 darcs_test = perl: -d "$ENV{MR_REPO}/_darcs"
-fossil_test = perl: -f "$ENV{MR_REPO}/_FOSSIL_"
+fossil_test = perl: -f "$ENV{MR_REPO}/_FOSSIL_" || -f "$ENV{MR_REPO}/.fslckout"
 git_bare_test = perl: 
 	-d "$ENV{MR_REPO}/refs/heads" && -d "$ENV{MR_REPO}/refs/tags" &&
 	-d "$ENV{MR_REPO}/objects" && -f "$ENV{MR_REPO}/config" &&
